<?php defined('BLUDIT') or die('Bludit CMS.'); ?>
{
    "title": "Medico 360",
    "slogan": "A project by 360 Muslim Experts",
    "description": "Congratulations you have successfully installed your Bludit.",
    "footer": "Copyright \u00a9 2025",
    "itemsPerPage": 6,
    "language": "en",
    "locale": "en, en_US, en_AU, en_CA, en_GB, en_IE, en_NZ",
    "timezone": "Asia\/Karachi",
    "theme": "blogx",
    "adminTheme": "booty",
    "homepage": "",
    "pageNotFound": "",
    "uriPage": "\/",
    "uriTag": "\/tag\/",
    "uriCategory": "\/category\/",
    "uriBlog": "",
    "url": "https:\/\/medico.360muslimexperts.com\/blog\/",
    "emailFrom": "no-reply@localhost",
    "orderBy": "date",
    "currentBuild": 20240806,
    "twitter": "https:\/\/twitter.com\/360MuslimExpert",
    "facebook": "https:\/\/www.facebook.com\/bluditcms",
    "codepen": "",
    "github": "https:\/\/github.com\/360MuslimExperts",
    "instagram": "",
    "gitlab": "",
    "linkedin": "",
    "xing": "",
    "telegram": "",
    "dateFormat": "F j, Y",
    "extremeFriendly": true,
    "autosaveInterval": 2,
    "titleFormatHomepage": "{{site-slogan}} | {{site-title}}",
    "titleFormatPages": "{{page-title}} | {{site-title}}",
    "titleFormatCategory": "{{category-name}} | {{site-title}}",
    "titleFormatTag": "{{tag-name}} | {{site-title}}",
    "imageRestrict": true,
    "imageRelativeToAbsolute": false
}